require"user.options"
require "user.keymap"
require "plugins.plugins"
-- require "user.onedark-setup"
-- require("dracula").load()
-- vim.cmd("colorscheme jellybeans-nvim")
require "user.neosolarized"
require "user.cmp"
require "user.lsp"
require "user.treesitter"
require "user.lualine"
require "user.ntree"
require "user.flutter"
require "user.bufferline"
require "user.comments"
